hostname: XX
commands_directory: XX
log_file: XX
api_token: XX
send_errors: true
tags: 
  - XX
#ignore_tag_commands:
#  - XX
commands:
  XX:
    command: XX
    #user: XX
    frequency: XX
    parameters:
      - XX